
package feilida.util.serviceNew;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ECologyServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ECologyServiceSoap {


    /**
     * 
     * @param buget
     * @return
     *     returns feilida.util.serviceNew.ArrayOfBudgetVO
     */
    @WebMethod(operationName = "QueryBudget", action = "http://tempuri.org/QueryBudget")
    @WebResult(name = "QueryBudgetResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryBudget", targetNamespace = "http://tempuri.org/", className = "feilida.util.serviceNew.QueryBudget")
    @ResponseWrapper(localName = "QueryBudgetResponse", targetNamespace = "http://tempuri.org/", className = "feilida.util.serviceNew.QueryBudgetResponse")
    public ArrayOfBudgetVO queryBudget(
        @WebParam(name = "buget", targetNamespace = "http://tempuri.org/")
        ArrayOfBudgetVO buget);

    /**
     * 
     * @param buget
     * @return
     *     returns feilida.util.serviceNew.ArrayOfBudgetVO
     */
    @WebMethod(operationName = "UpdateBudget", action = "http://tempuri.org/UpdateBudget")
    @WebResult(name = "UpdateBudgetResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateBudget", targetNamespace = "http://tempuri.org/", className = "feilida.util.serviceNew.UpdateBudget")
    @ResponseWrapper(localName = "UpdateBudgetResponse", targetNamespace = "http://tempuri.org/", className = "feilida.util.serviceNew.UpdateBudgetResponse")
    public ArrayOfBudgetVO updateBudget(
        @WebParam(name = "buget", targetNamespace = "http://tempuri.org/")
        ArrayOfBudgetVO buget);

}
